import {
  faChevronLeft,
  faChevronUp,
  faChevronDown,
  faChevronRight,
  faList,
  faUpload,
  faDatabase,
  faPodcast,
  faSnowflake,
  faStreetView,
  faBars,
  faTimes,
  faSearch,
  faEdit,
  faTrash,
  faCheck,
  faClipboardList,
  faHourglassHalf,
  faPen,
  faLock,
  faComment,
} from "@fortawesome/free-solid-svg-icons";
import { fab } from "@fortawesome/free-brands-svg-icons";

export const IconList = [
  fab,
  faChevronLeft,
  faChevronUp,
  faChevronDown,
  faChevronRight,
  faList,
  faUpload,
  faDatabase,
  faPodcast,
  faSnowflake,
  faStreetView,
  faBars,
  faTimes,
  faSearch,
  faEdit,
  faTrash,
  faCheck,
  faClipboardList,
  faHourglassHalf,
  faPen,
  faLock,
  faComment,
];
